# Source: https://netplan.io/examples/

# Configure ens160 for DHCP
#network:
#    version: 2
#    renderer: networkd
#    ethernets:
#        ens3:
#            dhcp4: true

# Configuring Static IP address 
# file stored on /etc/netplan/
# after changing run "sudo netplan apply" command
network:
    version: 2
    renderer: networkd
    ethernets:
        ens3:
            addresses:
                - 192.168.11.21/24
            nameservers:
                search: [lab.local]
                addresses: [208.67.222.222, 208.67.220.220]
            routes:
                - to: 0.0.0.0/0
                  via: 192.168.11.1